# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags: []

# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: "C_TAG",
      layout:
        [
          {
            id: 27,
            size: 0.05,
            x: 0,
            y: 0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 28,
            size: 0.05,
            x: 0,
            y: 0,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 29,
            size: 0.05,
            x: 0,
            y: -0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
        ],
    },
    {
      name: "R1_TAG",
      layout:
        [
          {
            id: 30,
            size: 0.05,
            x: 0,
            y: 0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 31,
            size: 0.05,
            x: 0,
            y: 0,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 32,
            size: 0.05,
            x: 0,
            y: -0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
        ],
    },
    {
      name: "R2_TAG",
      layout:
        [
          {
            id: 33,
            size: 0.05,
            x: 0,
            y: 0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 34,
            size: 0.05,
            x: 0,
            y: 0,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 35,
            size: 0.05,
            x: 0,
            y: -0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
        ],
    },
    {
      name: "R3_TAG",
      layout:
        [
          {
            id: 36,
            size: 0.05,
            x: 0,
            y: 0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 37,
            size: 0.05,
            x: 0,
            y: 0,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 38,
            size: 0.05,
            x: 0,
            y: -0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
        ],
    },
    {
      name: "R4_TAG",
      layout:
        [
          {
            id: 39,
            size: 0.05,
            x: 0,
            y: 0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 40,
            size: 0.05,
            x: 0,
            y: 0,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 41,
            size: 0.05,
            x: 0,
            y: -0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
        ],
    },
    {
      name: "P1_TAG",
      layout:
        [
          {
            id: 24,
            size: 0.05,
            x: 0,
            y: 0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 25,
            size: 0.05,
            x: 0,
            y: 0,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 26,
            size: 0.05,
            x: 0,
            y: -0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
        ],
    },
    {
      name: "P2_TAG",
      layout:
        [
          {
            id: 124,
            size: 0.05,
            x: 0,
            y: 0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 125,
            size: 0.05,
            x: 0,
            y: 0,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
          {
            id: 126,
            size: 0.05,
            x: 0,
            y: -0.1,
            qw: 0.7071068,
            qx: 0,
            qy: -0.7071068,
            qz: 0,
          },
        ],
    },
  ]
